server {
    server_name quiz.bruschatka.ru;

    root /var/www/quiz.bruschatka.ru/website/public;
    index index.php index.html;

    client_max_body_size 32M;

    access_log /var/log/nginx/quiz.bruschatka.ru.access.log;
    error_log /var/log/nginx/quiz.bruschatka.ru.error.log;

    location = /admin {
        return 301 /admin/;
    }

    location /admin/ {
        try_files $uri $uri/ /admin/index.html;
        index index.html;
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    listen 80;
}
